name: publish

on:
  release:
    types: [ published ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Add Test Pypi to repositories
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - name: Configure token
        run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}      
      - name: Build distribution
        run: poetry build
      - name: Publish to Test PyPI
        run: poetry publish --repository=testpypi
